#!/bin/sh
# Interactive setup script for ControlD DoH on Alta Labs Route 10
# Run this on the router: sh setup.sh

set -e

REPO_BASE="https://raw.githubusercontent.com/your-username/alta-route10-controld/main"
CURLD_VERSION="1.5.0"

echo "=== Alta Labs Route 10 + ControlD Setup ==="
echo ""

# Step 1: Get resolver ID
printf "Enter your ControlD Resolver ID (from controld.com dashboard): "
read -r RESOLVER_ID

if [ -z "$RESOLVER_ID" ]; then
    echo "Error: Resolver ID is required"
    exit 1
fi

echo ""
echo "Using resolver ID: $RESOLVER_ID"
echo ""

# Step 2: Check architecture
ARCH=$(uname -m)
echo "Detected architecture: $ARCH"
if [ "$ARCH" != "aarch64" ]; then
    echo "Warning: This script is tested on aarch64. Your architecture may not be supported."
    printf "Continue anyway? (y/n): "
    read -r CONFIRM
    [ "$CONFIRM" = "y" ] || exit 1
fi

# Step 3: Download ctrld
echo ""
echo "Downloading ctrld v${CURLD_VERSION}..."
cd /cfg
wget -O ctrld.tar.gz "https://github.com/Control-D-Inc/ctrld/releases/download/v${CURLD_VERSION}/ctrld_${CURLD_VERSION}_linux_arm64.tar.gz"
tar xzf ctrld.tar.gz -C /tmp
mv /tmp/dist/ctrld_${CURLD_VERSION}_linux_arm64/ctrld /cfg/ctrld
chmod +x /cfg/ctrld
rm -rf /tmp/dist ctrld.tar.gz
echo "ctrld downloaded to /cfg/ctrld"

# Step 4: Generate ctrld.toml
echo ""
echo "Generating /cfg/ctrld.toml..."
cat > /cfg/ctrld.toml << EOF
[service]
    log_level = "notice"
    cache_enable = true
    cache_size = 4096
    discover_dhcp = true
    discover_ptr = true
    discover_mdns = false
    discover_arp = true
    discover_hosts = true
    discover_refresh_interval = 60
    dhcp_lease_file_path = "/cfg/dhcp.leases"
    dhcp_lease_file_format = "dnsmasq"

[network.0]
    cidrs = ["0.0.0.0/0"]
    name = "Everyone"

[network.1]
    cidrs = ["192.168.1.0/24"]
    name = "LAN"

[network.2]
    cidrs = ["192.168.2.0/24"]
    name = "LAN2"

[upstream.0]
    bootstrap_ip = "76.76.2.22"
    endpoint = "https://dns.controld.com/${RESOLVER_ID}"
    name = "ControlD"
    timeout = 5000
    type = "doh"
    send_client_info = true

[listener.0]
    ip = "0.0.0.0"
    port = 5354
EOF
echo "ctrld.toml created"

# Step 5: Generate post-cfg.sh
echo ""
echo "Generating /cfg/post-cfg.sh..."
cat > /cfg/post-cfg.sh << 'POSTCFG'
#!/bin/sh
# ControlD DoH with per-device visibility on Alta Labs Route 10
# Auto-generated by setup.sh

while ! uci get https-dns-proxy.@https-dns-proxy[0] >/dev/null 2>&1; do sleep 1; done

uci set https-dns-proxy.@https-dns-proxy[0].resolver_url='https://dns.controld.com/RESOLVER_PLACEHOLDER'
uci set https-dns-proxy.@https-dns-proxy[0].bootstrap_dns='76.76.2.22'
uci set https-dns-proxy.@https-dns-proxy[1].resolver_url='https://dns.controld.com/RESOLVER_PLACEHOLDER'
uci set https-dns-proxy.@https-dns-proxy[1].bootstrap_dns='76.76.2.22'
uci set https-dns-proxy.@https-dns-proxy[2].resolver_url='https://dns.controld.com/RESOLVER_PLACEHOLDER'
uci set https-dns-proxy.@https-dns-proxy[2].bootstrap_dns='76.76.2.22'
uci commit https-dns-proxy
/etc/init.d/https-dns-proxy restart

uci delete dhcp.@dnsmasq[0].server 2>/dev/null
uci add_list dhcp.@dnsmasq[0].server='127.0.0.1#5053'
uci add_list dhcp.@dnsmasq[0].server='127.0.0.1#5054'
uci add_list dhcp.@dnsmasq[0].server='127.0.0.1#5055'
uci set dhcp.@dnsmasq[0].noresolv='0'
uci commit dhcp
/etc/init.d/dnsmasq restart

while ! ping -c1 76.76.2.22 >/dev/null 2>&1; do sleep 2; done

nohup /cfg/ctrld run -c /cfg/ctrld.toml -d >/dev/null 2>&1 &

n=0
while [ $n -lt 15 ]; do
    if nslookup google.com 127.0.0.1#5354 >/dev/null 2>&1; then
        break
    fi
    sleep 1
    n=`expr $n + 1`
done

if nslookup google.com 127.0.0.1#5354 >/dev/null 2>&1; then
    iptables -t nat -A PREROUTING -i br-lan -p udp --dport 53 -j REDIRECT --to-port 5354
    iptables -t nat -A PREROUTING -i br-lan -p tcp --dport 53 -j REDIRECT --to-port 5354
    iptables -t nat -A PREROUTING -i br-lan_2 -p udp --dport 53 -j REDIRECT --to-port 5354
    iptables -t nat -A PREROUTING -i br-lan_2 -p tcp --dport 53 -j REDIRECT --to-port 5354
    logger -t post-cfg 'ctrld started, DNS redirected to port 5354'
else
    logger -t post-cfg 'ctrld failed, using https-dns-proxy fallback'
fi
POSTCFG

# Replace placeholder with actual resolver ID
sed -i "s/RESOLVER_PLACEHOLDER/${RESOLVER_ID}/g" /cfg/post-cfg.sh
chmod +x /cfg/post-cfg.sh
echo "post-cfg.sh created"

# Step 6: Test ctrld before applying
echo ""
echo "Testing ctrld..."
nohup /cfg/ctrld run -c /cfg/ctrld.toml -d >/dev/null 2>&1 &
sleep 3

if nslookup google.com 127.0.0.1#5354 >/dev/null 2>&1; then
    echo "ctrld is working!"
else
    echo "Warning: ctrld did not respond to test query."
    echo "It may need more time. Continuing with setup."
fi

# Step 7: Apply
echo ""
echo "Applying configuration..."
/cfg/post-cfg.sh

echo ""
echo "=== Setup Complete ==="
echo ""
echo "Verify in your ControlD dashboard: https://controld.com"
echo "You should see individual devices with hostnames within a few minutes."
echo ""
echo "Configuration files:"
echo "  /cfg/ctrld         - ctrld binary"
echo "  /cfg/ctrld.toml    - ctrld configuration"
echo "  /cfg/post-cfg.sh   - boot persistence script"
echo ""
echo "To uninstall: rm /cfg/ctrld /cfg/ctrld.toml /cfg/post-cfg.sh && reboot"
