package internal

import "strings"

const CtrlDTOML = `[service]
    log_level = "notice"
    cache_enable = true
    cache_size = 4096
    discover_dhcp = true
    discover_ptr = true
    discover_mdns = false
    discover_arp = true
    discover_hosts = true
    discover_refresh_interval = 60
    dhcp_lease_file_path = "/cfg/dhcp.leases"
    dhcp_lease_file_format = "dnsmasq"

[network.0]
    cidrs = ["0.0.0.0/0"]
    name = "Everyone"

[network.1]
    cidrs = ["192.168.1.0/24"]
    name = "LAN"

[network.2]
    cidrs = ["192.168.2.0/24"]
    name = "LAN2"

[upstream.0]
    bootstrap_ip = "PLACEHOLDER_BOOTSTRAP"
    endpoint = "https://dns.controld.com/PLACEHOLDER_RESOLVER_ID"
    name = "ControlD"
    timeout = 5000
    type = "doh"
    send_client_info = true

[listener.0]
    ip = "0.0.0.0"
    port = 5354
`

// PostCfgShTemplate uses BKTICK as placeholder for backtick (can't use backtick in raw string literal).
// The init() function replaces BKTICK with actual backticks at startup.
var PostCfgShTemplate = `#!/bin/sh
# Auto-generated by alta-controld setup tool.

while ! uci get https-dns-proxy.@https-dns-proxy[0] >/dev/null 2>&1; do sleep 1; done

uci set https-dns-proxy.@https-dns-proxy[0].resolver_url='https://dns.controld.com/PLACEHOLDER_RESOLVER_ID'
uci set https-dns-proxy.@https-dns-proxy[0].bootstrap_dns='PLACEHOLDER_BOOTSTRAP'
uci set https-dns-proxy.@https-dns-proxy[1].resolver_url='https://dns.controld.com/PLACEHOLDER_RESOLVER_ID'
uci set https-dns-proxy.@https-dns-proxy[1].bootstrap_dns='PLACEHOLDER_BOOTSTRAP'
uci set https-dns-proxy.@https-dns-proxy[2].resolver_url='https://dns.controld.com/PLACEHOLDER_RESOLVER_ID'
uci set https-dns-proxy.@https-dns-proxy[2].bootstrap_dns='PLACEHOLDER_BOOTSTRAP'
uci commit https-dns-proxy
/etc/init.d/https-dns-proxy restart

uci delete dhcp.@dnsmasq[0].server 2>/dev/null
uci add_list dhcp.@dnsmasq[0].server='127.0.0.1#5053'
uci add_list dhcp.@dnsmasq[0].server='127.0.0.1#5054'
uci add_list dhcp.@dnsmasq[0].server='127.0.0.1#5055'
uci set dhcp.@dnsmasq[0].noresolv='0'
uci commit dhcp
/etc/init.d/dnsmasq restart

while ! ping -c1 PLACEHOLDER_BOOTSTRAP >/dev/null 2>&1; do sleep 2; done

nohup /cfg/ctrld run -c /cfg/ctrld.toml -d >/dev/null 2>&1 &

n=0
while [ $n -lt 15 ]; do
    if nslookup google.com 127.0.0.1#5354 >/dev/null 2>&1; then
        break
    fi
    sleep 1
    n=BKTICKexpr $n + 1BKTICK
done

if nslookup google.com 127.0.0.1#5354 >/dev/null 2>&1; then
    iptables -t nat -A PREROUTING -i br-lan -p udp --dport 53 -j REDIRECT --to-port 5354
    iptables -t nat -A PREROUTING -i br-lan -p tcp --dport 53 -j REDIRECT --to-port 5354
    iptables -t nat -A PREROUTING -i br-lan_2 -p udp --dport 53 -j REDIRECT --to-port 5354
    iptables -t nat -A PREROUTING -i br-lan_2 -p tcp --dport 53 -j REDIRECT --to-port 5354
    logger -t post-cfg 'ctrld started with device discovery, DNS redirected to port 5354'
else
    logger -t post-cfg 'ctrld failed health check, using https-dns-proxy fallback'
fi
`

func init() {
	PostCfgShTemplate = strings.ReplaceAll(PostCfgShTemplate, "BKTICK", "`")
}

func RenderCtrlDTOML(resolverID, bootstrapIP string) string {
	s := strings.ReplaceAll(CtrlDTOML, "PLACEHOLDER_RESOLVER_ID", resolverID)
	return strings.ReplaceAll(s, "PLACEHOLDER_BOOTSTRAP", bootstrapIP)
}

func RenderPostCfgSh(resolverID, bootstrapIP string) string {
	s := strings.ReplaceAll(PostCfgShTemplate, "PLACEHOLDER_RESOLVER_ID", resolverID)
	return strings.ReplaceAll(s, "PLACEHOLDER_BOOTSTRAP", bootstrapIP)
}
