package internal

import "strings"

// CtrlDTOML is the template for /cfg/ctrld.toml
// PLACEHOLDER_RESOLVER_ID will be replaced with the user's resolver ID
// PLACEHOLDER_BOOTSTRAP will be replaced with the bootstrap IP
const CtrlDTOML = `[service]
    log_level = "notice"
    cache_enable = true
    cache_size = 4096
    discover_dhcp = true
    discover_ptr = true
    discover_mdns = false
    discover_arp = true
    discover_hosts = true
    discover_refresh_interval = 60
    dhcp_lease_file_path = "/cfg/dhcp.leases"
    dhcp_lease_file_format = "dnsmasq"

[network.0]
    cidrs = ["0.0.0.0/0"]
    name = "Everyone"

[network.1]
    cidrs = ["192.168.1.0/24"]
    name = "LAN"

[network.2]
    cidrs = ["192.168.2.0/24"]
    name = "LAN2"

[upstream.0]
    bootstrap_ip = "PLACEHOLDER_BOOTSTRAP"
    endpoint = "https://dns.controld.com/PLACEHOLDER_RESOLVER_ID"
    name = "ControlD"
    timeout = 5000
    type = "doh"
    send_client_info = true

[listener.0]
    ip = "0.0.0.0"
    port = 5354
`

// PostCfgShTemplate is the template for /cfg/post-cfg.sh (mutable for init replacement)
var PostCfgShTemplate = `#!/bin/sh
# ControlD DoH with per-device visibility on Alta Labs Route 10
# Auto-generated by alta-controld setup tool
# This script runs on every boot and re-applies the configuration.

# Wait for https-dns-proxy to initialize (kept as fallback)
while ! uci get https-dns-proxy.@https-dns-proxy[0] >/dev/null 2>&1; do sleep 1; done

# Set https-dns-proxy to ControlD as fallback
uci set https-dns-proxy.@https-dns-proxy[0].resolver_url='https://dns.controld.com/PLACEHOLDER_RESOLVER_ID'
uci set https-dns-proxy.@https-dns-proxy[0].bootstrap_dns='PLACEHOLDER_BOOTSTRAP'
uci set https-dns-proxy.@https-dns-proxy[1].resolver_url='https://dns.controld.com/PLACEHOLDER_RESOLVER_ID'
uci set https-dns-proxy.@https-dns-proxy[1].bootstrap_dns='PLACEHOLDER_BOOTSTRAP'
uci set https-dns-proxy.@https-dns-proxy[2].resolver_url='https://dns.controld.com/PLACEHOLDER_RESOLVER_ID'
uci set https-dns-proxy.@https-dns-proxy[2].bootstrap_dns='PLACEHOLDER_BOOTSTRAP'
uci commit https-dns-proxy
/etc/init.d/https-dns-proxy restart

# Restore dnsmasq to use https-dns-proxy (fallback)
uci delete dhcp.@dnsmasq[0].server 2>/dev/null
uci add_list dhcp.@dnsmasq[0].server='127.0.0.1#5053'
uci add_list dhcp.@dnsmasq[0].server='127.0.0.1#5054'
uci add_list dhcp.@dnsmasq[0].server='127.0.0.1#5055'
uci set dhcp.@dnsmasq[0].noresolv='0'
uci commit dhcp
/etc/init.d/dnsmasq restart

# Wait for network connectivity
while ! ping -c1 PLACEHOLDER_BOOTSTRAP >/dev/null 2>&1; do sleep 2; done

# Start ctrld as daemon with config file
nohup /cfg/ctrld run -c /cfg/ctrld.toml -d >/dev/null 2>&1 &

# Wait for ctrld to be ready (up to 15s)
n=0
while [ $n -lt 15 ]; do
    if nslookup google.com 127.0.0.1#5354 >/dev/null 2>&1; then
        break
    fi
    sleep 1
    n=BKTICKexpr $n + 1BKTICK
done

# Only redirect DNS if ctrld is confirmed working
if nslookup google.com 127.0.0.1#5354 >/dev/null 2>&1; then
    iptables -t nat -A PREROUTING -i br-lan -p udp --dport 53 -j REDIRECT --to-port 5354
    iptables -t nat -A PREROUTING -i br-lan -p tcp --dport 53 -j REDIRECT --to-port 5354
    iptables -t nat -A PREROUTING -i br-lan_2 -p udp --dport 53 -j REDIRECT --to-port 5354
    iptables -t nat -A PREROUTING -i br-lan_2 -p tcp --dport 53 -j REDIRECT --to-port 5354
    logger -t post-cfg 'ctrld started with device discovery, DNS redirected to port 5354'
else
    logger -t post-cfg 'ctrld failed health check, using https-dns-proxy fallback'
fi
`

// RenderCtrlDTOML replaces placeholders with actual values
func RenderCtrlDTOML(resolverID, bootstrapIP string) string {
	s := CtrlDTOML
	s = replaceAll(s, "PLACEHOLDER_RESOLVER_ID", resolverID)
	s = replaceAll(s, "PLACEHOLDER_BOOTSTRAP", bootstrapIP)
	return s
}

// RenderPostCfgSh replaces placeholders with actual values
func RenderPostCfgSh(resolverID, bootstrapIP string) string {
	s := PostCfgShTemplate
	s = replaceAll(s, "PLACEHOLDER_RESOLVER_ID", resolverID)
	s = replaceAll(s, "PLACEHOLDER_BOOTSTRAP", bootstrapIP)
	return s
}

func replaceAll(s, old, newVal string) string {
	result := ""
	for {
		idx := indexOf(s, old)
		if idx == -1 {
			break
		}
		result += s[:idx] + newVal
		s = s[idx+len(old):]
	}
	return result + s
}

func init() {
	// Replace BKTICK placeholders with actual backticks at init time
	PostCfgShTemplate = strings.ReplaceAll(PostCfgShTemplate, "BKTICK", "`")
}

func indexOf(s, substr string) int {
	for i := 0; i <= len(s)-len(substr); i++ {
		if s[i:i+len(substr)] == substr {
			return i
		}
	}
	return -1
}
